import React from 'react';
import clsx from 'clsx';
import Link from '@docusaurus/Link';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import Layout from '@theme/Layout';
import styles from './index.module.css';

function HomepageHeader() {
  const { siteConfig } = useDocusaurusContext();
  return (
    <header className={styles.heroBanner}>
      <div className="container">
        <h1 className={styles.heroTitle}>
          Master Your Learning Journey
        </h1>
        <p className={styles.heroSubtitle}>
          An intelligent platform powered by AI to help you learn faster, smarter, and more effectively.
        </p>
        <div className={styles.buttons}>
          <Link
            className="button button--primary button--lg"
            to="/auth/signup">
            Get Started Free
          </Link>
          <Link
            className="button button--secondary button--lg"
            to="/docs/intro">
            View Documentation
          </Link>
        </div>
      </div>
    </header>
  );
}

function Features() {
  const features = [
    {
      title: 'AI-Powered Learning',
      description: 'Get personalized content and summaries generated by advanced AI models tailored to your proficiency.',
      icon: '🤖'
    },
    {
      title: 'Progress Tracking',
      description: 'Monitor your learning journey with detailed analytics and progress reports to stay on track.',
      icon: '📊'
    },
    {
      title: 'Interactive Lessons',
      description: 'Engage with dynamic content, quizzes, and hands-on exercises to reinforce your knowledge.',
      icon: '💡'
    }
  ];

  return (
    <section className={styles.section}>
      <div className="container">
        <h2 className={styles.sectionTitle}>Why Choose Us?</h2>
        <div className={styles.features}>
          {features.map((feature, idx) => (
            <div key={idx} className={styles.featureCard}>
              <span className={styles.featureIcon}>{feature.icon}</span>
              <h3 className={styles.featureTitle}>{feature.title}</h3>
              <p className={styles.featureDesc}>{feature.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function CallToAction() {
  return (
    <section className={styles.ctaSection}>
      <div className="container">
        <h2 className={styles.ctaTitle}>Ready to Start Learning?</h2>
        <p className={styles.ctaDesc}>
          Join thousands of students who are already transforming their education with our platform.
        </p>
        <Link to="/auth/signup" className={styles.ctaButton}>
          Create Free Account
        </Link>
      </div>
    </section>
  );
}

export default function Home(): JSX.Element {
  const { siteConfig } = useDocusaurusContext();
  return (
    <Layout
      title={`Home | ${siteConfig.title}`}
      description="AI-powered learning platform">
      <HomepageHeader />
      <main>
        <Features />
        <CallToAction />
      </main>
    </Layout>
  );
}
